name: Deploy to EC2 Development

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DISKUSS_ADMIN_DEVELOPMENT_SSH_PRIVATE_KEY }}

    - name: SSH into EC2 and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@3.7.254.117 << 'EOF'
          cd ~/Diskuss-Admin
          git pull origin main
          npm install
          pm2 restart KC-admin-dev 
        EOF
